version: '3'

services:


  base_image:
    image: phaustin/base:may19
    build:
      context: base_image
    container_name: base_may19
    labels:
      - "traefik.enable=false"
  
  nbgrader:
    image: phaustin/nbgrader:may19
    depends_on:
      - base_image
    volumes:
      - ./data_share:/home/jovyan/work/data_share
      - ./source:/home/jovyan/work/source
      - ./exchange:/home/jovyan/work/exchange
      - ./release:/home/jovyan/work/release
      - ./submitted:/home/jovyan/work/submitted
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook","--NotebookApp.token=''","--debug"]
    build:
      context: nbgrader_image
    container_name: nbgrader_may19
    labels:
      - "traefik.enable=false"
